### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by grs83** [grs83/realtor-connection#9]
# Motivation:
Refactoring increases readability and maintainability of the code base.

# task: 
Client:
- [ ] Move fetch request into their own service object.
    - [ ] Make a services folder.
    - [ ] Create a .js file to hold your API service.

Server:
- [ ] Add error handler middleware.
- [ ] Create service objects for the request.
